/* 
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Splitit.SDK.Client.Client.SwaggerDateConverter;

namespace Splitit.SDK.Client.Model
{
    /// <summary>
    /// Disputes
    /// </summary>
    [DataContract]
    public partial class Disputes :  IEquatable<Disputes>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Disputes" /> class.
        /// </summary>
        /// <param name="inDispute">inDispute.</param>
        /// <param name="evidenceProvidedOn">evidenceProvidedOn.</param>
        public Disputes(bool? inDispute = default(bool?), DateTime? evidenceProvidedOn = default(DateTime?))
        {
            this.InDispute = inDispute;
            this.EvidenceProvidedOn = evidenceProvidedOn;
        }

        
        /// <summary>
        /// Gets or Sets InDispute
        /// </summary>
        [DataMember(Name="InDispute", EmitDefaultValue=false)]
        public bool? InDispute { get; set; }

        /// <summary>
        /// Gets or Sets EvidenceProvidedOn
        /// </summary>
        [DataMember(Name="EvidenceProvidedOn", EmitDefaultValue=false)]
        public DateTime? EvidenceProvidedOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Disputes {\n");
            sb.Append("  InDispute: ").Append(InDispute).Append("\n");
            sb.Append("  EvidenceProvidedOn: ").Append(EvidenceProvidedOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Disputes);
        }

        /// <summary>
        /// Returns true if Disputes instances are equal
        /// </summary>
        /// <param name="input">Instance of Disputes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Disputes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InDispute == input.InDispute ||
                    (this.InDispute != null &&
                    this.InDispute.Equals(input.InDispute))
                ) && 
                (
                    this.EvidenceProvidedOn == input.EvidenceProvidedOn ||
                    (this.EvidenceProvidedOn != null &&
                    this.EvidenceProvidedOn.Equals(input.EvidenceProvidedOn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InDispute != null)
                    hashCode = hashCode * 59 + this.InDispute.GetHashCode();
                if (this.EvidenceProvidedOn != null)
                    hashCode = hashCode * 59 + this.EvidenceProvidedOn.GetHashCode();
                return hashCode;
            }
        }
    }

}
