/* 
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Splitit.SDK.Client.Client.SwaggerDateConverter;

namespace Splitit.SDK.Client.Model
{
    /// <summary>
    /// Defines PaymentMethods
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum PaymentMethods
    {
        
        /// <summary>
        /// Enum ApplePay for value: ApplePay
        /// </summary>
        [EnumMember(Value = "ApplePay")]
        ApplePay = 1,
        
        /// <summary>
        /// Enum GooglePay for value: GooglePay
        /// </summary>
        [EnumMember(Value = "GooglePay")]
        GooglePay = 2,
        
        /// <summary>
        /// Enum CreditCard for value: CreditCard
        /// </summary>
        [EnumMember(Value = "CreditCard")]
        CreditCard = 3,
        
        /// <summary>
        /// Enum PaysafeIssuedCardID for value: PaysafeIssuedCardID
        /// </summary>
        [EnumMember(Value = "PaysafeIssuedCardID")]
        PaysafeIssuedCardID = 4
    }

}
