/*
 * splitit-web-api-public-sdk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.splitit.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Disputes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-15T17:05:16.705Z")
public class Disputes  {
  @SerializedName("InDispute")
  private Boolean inDispute = null;

  @SerializedName("EvidenceProvidedOn")
  private OffsetDateTime evidenceProvidedOn = null;

  public Disputes inDispute(Boolean inDispute) {
    this.inDispute = inDispute;
    return this;
  }

   /**
   * Get inDispute
   * @return inDispute
  **/
  @ApiModelProperty(value = "")
  public Boolean isInDispute() {
    return inDispute;
  }

  public void setInDispute(Boolean inDispute) {
    this.inDispute = inDispute;
  }

  public Disputes evidenceProvidedOn(OffsetDateTime evidenceProvidedOn) {
    this.evidenceProvidedOn = evidenceProvidedOn;
    return this;
  }

   /**
   * Get evidenceProvidedOn
   * @return evidenceProvidedOn
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEvidenceProvidedOn() {
    return evidenceProvidedOn;
  }

  public void setEvidenceProvidedOn(OffsetDateTime evidenceProvidedOn) {
    this.evidenceProvidedOn = evidenceProvidedOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Disputes disputes = (Disputes) o;
    return Objects.equals(this.inDispute, disputes.inDispute) &&
        Objects.equals(this.evidenceProvidedOn, disputes.evidenceProvidedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inDispute, evidenceProvidedOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Disputes {\n");
    
    
    sb.append("    inDispute: ").append(toIndentedString(inDispute)).append("\n");
    sb.append("    evidenceProvidedOn: ").append(toIndentedString(evidenceProvidedOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

