/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DisputeStatus {
    Open = 'Open',
    Won = 'Won',
    Lost = 'Lost',
    Closed = 'Closed',
    Other = 'Other'
}

export function DisputeStatusFromJSON(json: any): DisputeStatus {
    return DisputeStatusFromJSONTyped(json, false);
}

export function DisputeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisputeStatus {
    return json as DisputeStatus;
}

export function DisputeStatusToJSON(value?: DisputeStatus | null): any {
    return value as any;
}

