/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Disputes
 */
export interface Disputes {
    /**
     * 
     * @type {boolean}
     * @memberof Disputes
     */
    inDispute?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Disputes
     */
    evidenceProvidedOn?: Date;
}

export function DisputesFromJSON(json: any): Disputes {
    return DisputesFromJSONTyped(json, false);
}

export function DisputesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Disputes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inDispute': !exists(json, 'InDispute') ? undefined : json['InDispute'],
        'evidenceProvidedOn': !exists(json, 'EvidenceProvidedOn') ? undefined : (new Date(json['EvidenceProvidedOn'])),
    };
}

export function DisputesToJSON(value?: Disputes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'InDispute': value.inDispute,
        'EvidenceProvidedOn': value.evidenceProvidedOn === undefined ? undefined : (value.evidenceProvidedOn.toISOString()),
    };
}


