/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-public-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PaymentMethods {
    ApplePay = 'ApplePay',
    GooglePay = 'GooglePay',
    CreditCard = 'CreditCard',
    PaysafeIssuedCardID = 'PaysafeIssuedCardID'
}

export function PaymentMethodsFromJSON(json: any): PaymentMethods {
    return PaymentMethodsFromJSONTyped(json, false);
}

export function PaymentMethodsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethods {
    return json as PaymentMethods;
}

export function PaymentMethodsToJSON(value?: PaymentMethods | null): any {
    return value as any;
}

